name: MultiArrow
main: com.ayan4m1.multiarrow.MultiArrow
author: ayan4m1
version: 0.8
permissions:
    multiarrow.use.all:
        default: op
        description: Allows use of all arrow types
    multiarrow.free:
        default: op
        description: Bypass checks for extra materials
    multiarrow.infinite:
        default: false
        description: Will not not consume arrows when firing