name: MultiArrow
main: com.ayan4m1.multiarrow.MultiArrow
author: ayan4m1
version: 0.6
permissions:
    multiarrow.use.all:
        default: op
        description: Allows use of all arrow types
    multiarrow.free:
        default: op
        description: Users with this will not be required to provide extra materials
